[tool.poetry]
authors = ["Daven Quinn <dev@davenquinn.com>"]
description = "Diff-based database migrations"
name = "dinosaur"
packages = [
  {include = "sparrow"}, # only use from="src" if that is how you've structured your code.
]
version = "0.1.0"

[tool.poetry.dependencies]
GeoAlchemy2 = "^0.9.4"
SQLAlchemy = "^1.4.26"
SQLAlchemy-Utils = "^0.37.0"
psycopg2-binary = "^2.9.1"
python = "^3.8"
schemainspect = "^3.0.1616029793"
"sparrow.birdbrain" = ""
"sparrow.utils" = ""
sqlparse = "^0.4.0"

[tool.poetry.dev-dependencies]
"birdbrain" = {path = "../birdbrain", develop = true}
"macrostrat.core_utils" = {path = "../core-utils", develop = true}

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
