site_name: Macrostrat Python libraries
theme:
  name: "material"
nav:
  - Home: "index.md"
  - Macrostrat:
      - App Frame: "macrostrat/app-frame.md"
      - Database: "macrostrat/database.md"

plugins:
  - search
  - mkdocstrings
