site_name: Macrostrat Python libraries
theme:
  name: "material"
nav:
  - Home: "index.md"
  - Macrostrat:
      - Database: "macrostrat/database.md"
      - Dinosaur: "macrostrat/dinosaur.md"
      - Package Tools: "macrostrat/package_tools.md"
      - Utils: "macrostrat/utils.md"

plugins:
  - search
  - mkdocstrings
