#!/usr/bin/env python
"""
Run a long-running query to test if we can interrupt it.
"""

from sys import argv

from macrostrat.database import Database

db_conn = argv[1]
print(f"Connecting to {db_conn}")

db = Database(db_conn)

db.run_sql("SELECT pg_sleep(10);")

