/*
The `raster_layers` index: named raster *layers* (mosaics) and the individual
cloud-optimized rasters that make them up.

The schema name is deliberately `raster_layers` rather than `raster` or `rasters`
to avoid colliding with PostGIS Raster's vocabulary — nothing here stores pixels.
A row in `raster` is a *reference* to a COG living in an object store, plus the
metadata needed to decide whether that COG is worth reading for a given tile.
*/

CREATE SCHEMA IF NOT EXISTS raster_layers;

/*
A layer is a mosaic: an addressable name that a tile route can serve, standing
in for a set of rasters that should be composited together.

`minzoom`/`maxzoom`/`rescale_range` are *defaults* — a raster may override them,
and per-raster values always win (see `raster_layers.get_rasters`).
*/
CREATE TABLE IF NOT EXISTS raster_layers.layer (
  slug text PRIMARY KEY,
  name text,
  description text,
  minzoom integer,
  maxzoom integer,
  -- [min, max] used to scale raw values into a byte range at render time.
  rescale_range numeric[],
  -- Optional default colormap, in rio-tiler's `{value: [r,g,b,a]}` form (for
  -- categorical data) or as a named colormap.
  colormap jsonb,
  metadata jsonb
);

/*
A single cloud-optimized raster.

`href` is the canonical location GDAL/rio-tiler will open: an `s3://` URL, an
`https://` URL, or a local path for testing. It is unique across the index, so
re-registering the same raster updates it in place rather than duplicating it.

`footprint` is in EPSG:4326 and is currently the raster's bounding box; the
column is typed `geometry` (not `polygon`) so a mask-derived, non-rectangular
footprint can replace it later without a migration.
*/
CREATE TABLE IF NOT EXISTS raster_layers.raster (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  layer text NOT NULL REFERENCES raster_layers.layer(slug) ON UPDATE CASCADE,
  -- Short human-readable identifier, unique within the layer.
  slug text NOT NULL,
  href text NOT NULL,
  footprint geometry(Geometry, 4326) NOT NULL,
  -- Native zoom range, derived from the raster's resolution.
  minzoom integer,
  maxzoom integer,
  dtype text,
  nbands integer,
  nodata double precision,
  -- Native CRS, as an authority string (e.g. `EPSG:4326`) where one is known.
  crs text,
  rescale_range numeric[],
  -- Full reader metadata, kept verbatim for provenance and later reprocessing.
  info jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT raster_href_unique UNIQUE (href),
  CONSTRAINT raster_layer_slug_unique UNIQUE (layer, slug)
);

CREATE INDEX IF NOT EXISTS raster_footprint_idx
  ON raster_layers.raster USING GIST (footprint);

-- Asset selection filters by layer before it filters by geometry.
CREATE INDEX IF NOT EXISTS raster_layer_idx
  ON raster_layers.raster (layer);
