name: Continuous integration testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      # Bundling
      - name: Install Python libraries 
        run: poetry install && make

      - name: Run tests
        run: make test

      # - name: Run Sparrow integration tests
      #   run: sparrow test integration
